# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a47331d00a164aab99d1bf9db3f2ecccc17db6c57f8c7bf312e3d064e856a08f205e77a0c2c130625b0afbf871103ad8c8ddff502f8cdb1ad2e60ae411b9a39

test:
  secret_key_base: 4f85cb5fadeea621c3286744ba78773666b1579e816377bdde58adfd4cf701fec11a3406edbb2a02b6a8bdac2a080b4222819dc4e14034fc3942530457399ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
